function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end
Citizen.CreateThread(function()
    AddTextEntry('11caprice', 'Caprice 2011') -- Enter Gamename from vehicles.lua and what you want it to display.
    AddTextEntry('16explorer', 'Explorer 2016')
    AddTextEntry('16taurus', 'Taurus 2016')
    AddTextEntry('18charger', 'Charger 2018')
    AddTextEntry('18tahoe', 'Tahoe 2018')
    AddTextEntry('rapide', 'Rapide 2010')
	 AddTextEntry('rs318', 'Audi RS318')
	 AddTextEntry('x6m', 'BMW X6M F16')
	 AddTextEntry('4b', 'Silverado Mecanico')
	 AddTextEntry('m3', 'BMW M3')
	 AddTextEntry('divo', 'Bugatti Divo 2019')
	 AddTextEntry('69charger', 'Charger 1969')
	 AddTextEntry('chevette', 'Chevette 1992')
	 AddTextEntry('chevettestd', 'Chevette 1992')
	 AddTextEntry('maliboohoo', 'Malibu 1980')
	 AddTextEntry('16challenger', 'Challenger 2016')
	 AddTextEntry('ram2500', 'Ram2500 2019')
	 AddTextEntry('f812', 'Ferrari 812')
	 AddTextEntry('boss429', 'Mustang boss429')
	 AddTextEntry('mustang19', 'Mustang 2019')
	 AddTextEntry('boss302', 'Mustang Boss302')
	 AddTextEntry('mustangmach1', 'Mustang Mach1')
	 AddTextEntry('mustang65', 'Mustang 65')
	 AddTextEntry('f150', 'Raptor F150')
	 AddTextEntry('gmcyd', 'GMC YUKON 2015')
	 AddTextEntry('fk8', 'Civic 2019 Type R')
	 AddTextEntry('fnfcivic', 'Civic Civic 1993')
	 AddTextEntry('dc2','Honda Integra')
	 AddTextEntry('na1', 'NSX 1992')
	 AddTextEntry('catalina', 'Pontiac Catalina')
	 AddTextEntry('ap2', 'Honda S2000')
	 AddTextEntry('h6', 'Hummer H6')
	 AddTextEntry('demonhawk', 'Cherokee Demonhawk')
	 AddTextEntry('srt8', 'Cherokee SRT8')
	 AddTextEntry('srt8b', 'Cherokee SRT8')
	 AddTextEntry('lp770', 'Lambo Centenario')
	 AddTextEntry('urus', 'Lambo Urus')
	 AddTextEntry('rx7cwest', 'Mazda RX7')
	 AddTextEntry('sc18', 'Lambo Veneno')
	 AddTextEntry('rx7tunable', 'Mazda RX7 Devolver')
	 AddTextEntry('rx7tunable2', 'RX7 Special')
	 AddTextEntry('vsrx7', 'Mazda VSRX7')
	 AddTextEntry('e63amg', 'E63 AMG')
	 AddTextEntry('g65amg', 'Mercedes Serie G')
	 AddTextEntry('eclipse', 'Eclipse 1998')
	 AddTextEntry('evo9', 'Evolution 9')
	 AddTextEntry('lanex400', 'Evolution 2013')
	 AddTextEntry('gtr', 'Nissan GTR')
	 AddTextEntry('skyline', 'Nissan Skyline')
	 AddTextEntry('pgt3', 'Porshe GT3')
	 AddTextEntry('autana97', 'Autana 1997')
	 AddTextEntry('gt86', 'Toyota GT86')
	 AddTextEntry('brzbn', 'Toyota GT86')
	 AddTextEntry('fj40', 'FJ-40')
	 AddTextEntry('17toylc', 'Machito 2013')
	 AddTextEntry('supra2', 'Supra 1993')
	 AddTextEntry('tr22', 'Tesla R')
	 AddTextEntry('models', 'Tesla S')
	 AddTextEntry('supra19', 'Supra 2019')
	 AddTextEntry('pressuv', 'Cadillac Limo')
	 AddTextEntry('vantage', 'Aston Martin Vantage')
	 AddTextEntry('db11', 'Aston Martin db11')
	 AddTextEntry('650slw', 'McLaren	650slw')
	 AddTextEntry('p1', 'McLaren p1')
	 AddTextEntry('720s', 'McLaren 720s')
	 AddTextEntry('hevo', 'Lambo Huracan')
	 AddTextEntry('f430s', 'Ferrari f430s')
	 AddTextEntry('fm488', 'Ferrari fm488')
	 AddTextEntry('aperta', 'La Ferrari')
	 AddTextEntry('mig', 'Enzo Ferrari')
	 AddTextEntry('f40', 'Ferrari F40')
	 AddTextEntry('nlargo', 'Ferrari nlargo')
	 AddTextEntry('458speciale', 'Ferrari 458speciale')
	 AddTextEntry('fstradale', 'Ferrari fstradale')
	 AddTextEntry('pista', 'Ferrari pista')
	 AddTextEntry('ferporto', 'Ferrari ferporto')
	AddTextEntry('fpacehm', 'Jaguar fpacehm')
	AddTextEntry('nh2r', 'Ninja2 nh2r')
	AddTextEntry('vxr', 'Land Cruiser 2016')
	AddTextEntry('r1', 'R1')
	AddTextEntry('500x', 'CB500x')
	AddTextEntry('sxf450sm', 'Sxf450sm')
	AddTextEntry('rsv4', 'Rsv4')
	AddTextEntry('r6', 'R6')
	AddTextEntry('gsxr', 'Gsxr')
	AddTextEntry('dabob', 'Darmon')
	AddTextEntry('desmo', 'Ducati Desmo')
	AddTextEntry('nh2r', 'Ninja 2')
	AddTextEntry('f4rr', 'F4RR')
	AddTextEntry('hvrod2', 'HVrod2')
	AddTextEntry('goldwing', 'Goldwing')
--    AddTextEntry('SQ72016', 'Audi SQ7')
 --   AddTextEntry('rs3', '2018 Audi RS3 Sportback')
end)